USE vvr160b5ib65hzjq;
INSERT INTO Usersmeta (content, content_type) VALUES ('RYlCVwxoL_g', 'youtube');
INSERT INTO Usersmeta (content, content_type) VALUES ('PyDlBy5tgYA', 'youtube');
INSERT INTO Usersmeta (content, content_type) VALUES ('Utv9rCHlpkM', 'youtube');
INSERT INTO Usersmeta (content, content_type) VALUES ('UF8uR6Z6KLc', 'youtube');
INSERT INTO Usersmeta (content, content_type) VALUES ('WO4tIrjBDkk', 'youtube');
INSERT INTO Usersmeta (content, content_type) VALUES ('zy9aj-dr118', 'youtube');
INSERT INTO Usersmeta (content, content_type) VALUES ('qKBEY9HoDAg', 'youtube');
INSERT INTO Usersmeta (content, content_type) VALUES ('PQleT6BtCbE', 'youtube');
INSERT INTO Usersmeta (content, content_type) VALUES ('lCN6FjqDcHg', 'youtube');
INSERT INTO Usersmeta (content, content_type) VALUES ('iADTpgRXYrk', 'youtube');
INSERT INTO Usersmeta (content, content_type) VALUES ('6P2nPI6CTlc', 'youtube');
INSERT INTO Usersmeta (content, content_type) VALUES ('11RKiZ1S0e4', 'youtube');
INSERT INTO Usersmeta (content, content_type) VALUES ('2nBI3iWLhupR7LyAJ5GGkE', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('4hszow3YBRAbGGA0WbbR6r', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('2RUFzxyUlI36KKy9Agkqze', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('5YJIdKE76GacbcTxuoOf93', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('6Q32Vkucx2qeuVyBd3NiFZ', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('6CfjAVG9FwmwRtxE8yEWlu', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('4F64QXRV1EGHSm5jIeMmcQ', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('7vwkKw2Xd7Pks1X712Au0T', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('0qvAz8C10uJ8PvGvJokgIF', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('3Rw4FB6mAFNZzCWvZZOsIo', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('0aFObVR01JzPbBMjze4xPV', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('2DGhuqg4PkU4N1ubtJhQQb', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('54ix2V2omFv9UUiMks7Fhf', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('6VBUM9tmOS6tPT11yoFktm', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('24H5KPBdSvHQMRXTp12K3J', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('1R6sDs5ovdcweZlFzGxQVD', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('7Duqn8un04Nz5n4PWk83Q5', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('4syv1QpthkeCBcLSw0Ldpf', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('4bz7uB4edifWKJXSDxwHcs', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('1mjQfuj2qBcRXQZSoHUqUs', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('4sjLcE0GQ6urc4iUXsUPe9', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('2jhyJeAlhg4fLd0B4OQKhM', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('4WHPdjmqPvlAVqZZhq5RAt', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('5xKVYMxOHB2XRLCUafFrz6', 'spotify');
INSERT INTO Usersmeta (content, content_type) VALUES ('The best preparation for tomorrow is doing your best today. - H. Jackson Brown, Jr.', 'quotes');
INSERT INTO Usersmeta (content, content_type) VALUES ('Put your heart, mind, and soul into even your smallest acts. This is the secret of success. - Swami Sivananda', 'quotes');
INSERT INTO Usersmeta (content, content_type) VALUES ('We should certainly count our blessings, but we should also make our blessings count. - Neal Maxwel', 'quotes');
INSERT INTO Usersmeta (content, content_type) VALUES ('They say a person needs just three things to be truly happy in this world: someone to love, something to do, and something to hope for. - Tom Bodett', 'quotes');
INSERT INTO Usersmeta (content, content_type) VALUES ('Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis', 'quotes');
INSERT INTO Usersmeta (content, content_type) VALUES ('No soul that aspires can ever fail to rise; no heart that loves can ever be abandoned. Difficulties exist only that in overcoming them we may grow strong, and they who have suffered are able to save. - Annie Besant', 'quotes');
INSERT INTO Usersmeta (content, content_type) VALUES ('Although the world is full of suffering, it is full also of the overcoming it. - Helen Keller', 'quotes');
INSERT INTO Usersmeta (content, content_type) VALUES ('Rock bottom became the solid foundation on which I rebuilt my life. - J.K. Rowling', 'quotes');
INSERT INTO Usersmeta (content, content_type) VALUES ('When we face the worst that can happen in any situation, we grow. When circumstances are at their worst, we can find our best. - Elisabeth Kübler-Ross', 'quotes');
INSERT INTO Usersmeta (content, content_type) VALUES ('You express the truth of your character with the choice of your actions. - Steve Maraboli', 'quotes');
INSERT INTO Usersmeta (content, content_type) VALUES ('You don’t inspire your teammates by showing them how amazing you are. You inspire them by showing them how amazing they are. - Robyn Benincasa', 'quotes');
